include:
  - template: Kaniko.gitlab-ci.yml

kaniko-build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    KANIKO_REGISTRY_MIRROR: registry.math.cnrs.fr
    DOCKERFILE_PATH: docker/nginx-unit/Dockerfile
    IMAGE_TAG: "$CI_REGISTRY_IMAGE:stable --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
  extends:
    - .kaniko-build
