include:
  - template: Kaniko.gitlab-ci.yml

kaniko-build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    DOCKERFILE_PATH: docker/nginx-unit/Dockerfile
  extends:
    - .kaniko-build
